app = "app-wispy-leaf-5983"
primary_region = "cdg"

[build]
  dockerfile = "Dockerfile"

[env]
  PORT = "8080"

[[services]]
  internal_port = 8080
  protocol = "tcp"

  [[services.ports]]
    port = 80
    handlers = []

  [[services.ports]]
    port = 443
    handlers = ["tls"]

  [services.concurrency]
    type = "connections"
    hard_limit = 500
    soft_limit = 400

[[vm]]
  memory = "256mb"
  cpu_kind = "shared"
  cpus = 1
